- name: Install frontend components
  become: yes
  hosts: frontend
  tasks:
  - name: disable nginx server
    ansible.builtin.command: dnf module disable nginx -y 

  - name: enable nginx:1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -yes

  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

